-- Mock Tutorials Data (1000 records)
-- Add created_by and subscription_needed columns first if they don't exist
-- ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS created_by VARCHAR(255) NOT NULL DEFAULT 'Admin';
-- ALTER TABLE tutorials ADD COLUMN IF NOT EXISTS subscription_needed BOOLEAN NOT NULL DEFAULT false;

INSERT INTO tutorials (title, description, published, created_by, subscription_needed) VALUES
('Getting Started with JavaScript', 'Learn the basics of JavaScript programming language', true, 'John Smith', false),
('Advanced React Patterns', 'Deep dive into advanced React design patterns and best practices', true, 'Sarah Johnson', true),
('Node.js REST API Development', 'Build scalable REST APIs using Node.js and Express', true, 'Michael Chen', false),
('TypeScript Fundamentals', 'Master TypeScript for type-safe JavaScript development', false, 'Emily Davis', true),
('SQL Database Design', 'Learn how to design efficient relational databases', true, 'David Miller', false),
('Python for Data Science', 'Introduction to data analysis with Python and pandas', true, 'Lisa Anderson', true),
('Docker Containerization', 'Containerize your applications with Docker', true, 'Robert Wilson', false),
('Kubernetes Orchestration', 'Deploy and manage containerized applications at scale', false, 'Jennifer Taylor', true),
('AWS Cloud Computing', 'Build and deploy applications on Amazon Web Services', true, 'James Brown', true),
('Git Version Control', 'Master Git for effective version control', true, 'Maria Garcia', false),
('CSS Grid Layout', 'Create modern layouts with CSS Grid', true, 'Christopher Lee', false),
('Flexbox Mastery', 'Complete guide to CSS Flexbox layout system', true, 'Amanda Martinez', false),
('Vue.js Component Development', 'Build reusable components with Vue.js framework', false, 'Daniel Rodriguez', true),
('Angular Services and Dependency Injection', 'Master Angular services and DI patterns', true, 'Jessica Hernandez', true),
('MongoDB Database Administration', 'Manage and optimize MongoDB databases', true, 'Matthew Lopez', false),
('Redis Caching Strategies', 'Implement effective caching with Redis', true, 'Ashley Gonzalez', true),
('GraphQL API Design', 'Design and build GraphQL APIs from scratch', false, 'Joshua Wilson', true),
('Webpack Module Bundling', 'Configure and optimize Webpack for your projects', true, 'Stephanie Anderson', false),
('Jest Unit Testing', 'Write comprehensive unit tests with Jest', true, 'Andrew Thomas', false),
('Cypress End-to-End Testing', 'Automate browser testing with Cypress', true, 'Nicole Taylor', true),
('Next.js Server-Side Rendering', 'Build SEO-friendly apps with Next.js SSR', true, 'Brandon Moore', true),
('Gatsby Static Site Generation', 'Create blazing fast static sites with Gatsby', false, 'Melissa Jackson', false),
('Express.js Middleware', 'Understanding and creating Express middleware', true, 'Kevin Martin', false),
('Socket.io Real-time Communication', 'Build real-time applications with Socket.io', true, 'Laura Thompson', true),
('OAuth 2.0 Authentication', 'Implement secure OAuth authentication flows', true, 'Ryan White', true),
('JWT Token Management', 'Secure your APIs with JSON Web Tokens', true, 'Rachel Harris', false),
('Responsive Web Design', 'Create mobile-friendly responsive websites', true, 'Jason Clark', false),
('Progressive Web Apps', 'Build installable PWAs with modern web technologies', false, 'Michelle Lewis', true),
('Web Accessibility Standards', 'Make your websites accessible to everyone', true, 'Eric Robinson', false),
('SEO Best Practices', 'Optimize your website for search engines', true, 'Kimberly Walker', false),
('Chrome DevTools Debugging', 'Master browser debugging with Chrome DevTools', true, 'Steven Hall', false),
('Performance Optimization', 'Speed up your web applications', true, 'Patricia Allen', true),
('Webpack Configuration Advanced', 'Deep dive into advanced Webpack configurations', false, 'Timothy Young', true),
('Babel JavaScript Transpilation', 'Configure Babel for modern JavaScript', true, 'Rebecca Hernandez', false),
('ESLint Code Quality', 'Enforce code quality with ESLint', true, 'Justin King', false),
('Prettier Code Formatting', 'Automate code formatting with Prettier', true, 'Samantha Wright', false),
('TailwindCSS Utility-First CSS', 'Build UIs quickly with TailwindCSS', true, 'Aaron Lopez', true),
('Bootstrap Framework Basics', 'Rapid prototyping with Bootstrap framework', true, 'Katherine Hill', false),
('Material-UI Components', 'Build beautiful UIs with Material-UI', false, 'Nathan Scott', true),
('Ant Design UI Library', 'Enterprise UI components with Ant Design', true, 'Victoria Green', false),
('Redux State Management', 'Manage application state with Redux', true, 'Jordan Adams', true),
('MobX Reactive State', 'Simple state management with MobX', true, 'Brittany Baker', false),
('Zustand Lightweight State', 'Minimal state management with Zustand', false, 'Christian Nelson', true),
('Recoil State Library', 'Facebook''s state management for React', true, 'Danielle Carter', false),
('React Query Data Fetching', 'Powerful data synchronization with React Query', true, 'Austin Mitchell', true),
('SWR Data Fetching', 'Stale-while-revalidate data fetching strategy', true, 'Megan Perez', false),
('Axios HTTP Client', 'Make HTTP requests with Axios library', true, 'Tyler Roberts', false),
('Fetch API Modern Requests', 'Use the native Fetch API for HTTP requests', true, 'Alexis Turner', false),
('Formik Form Handling', 'Build and validate forms with Formik', false, 'Brandon Phillips', true),
('React Hook Form', 'Performant form library with React Hooks', true, 'Kayla Campbell', true),
('Yup Schema Validation', 'Validate data with Yup schemas', true, 'Dylan Parker', false),
('Joi Validation Library', 'Server-side validation with Joi', true, 'Amber Evans', false),
('bcrypt Password Hashing', 'Secure password storage with bcrypt', true, 'Marcus Edwards', true),
('Passport.js Authentication', 'Flexible authentication middleware for Node.js', true, 'Courtney Collins', false),
('Helmet.js Security', 'Secure Express apps with HTTP headers', true, 'Cody Stewart', false),
('CORS Configuration', 'Handle Cross-Origin Resource Sharing properly', true, 'Sierra Sanchez', false),
('Rate Limiting APIs', 'Protect your APIs with rate limiting', false, 'Caleb Morris', true),
('SQL Injection Prevention', 'Secure your database queries against SQL injection', true, 'Jasmine Rogers', true),
('XSS Attack Prevention', 'Protect against Cross-Site Scripting attacks', true, 'Garrett Reed', true),
('CSRF Protection', 'Implement CSRF token validation', true, 'Natalie Cook', false),
('Content Security Policy', 'Enhance security with CSP headers', true, 'Ethan Morgan', false),
('HTTPS and SSL/TLS', 'Secure communications with HTTPS', true, 'Haley Bell', true),
('Web Scraping with Puppeteer', 'Automate browser tasks with Puppeteer', false, 'Ian Murphy', true),
('Cheerio HTML Parsing', 'Parse and manipulate HTML with Cheerio', true, 'Maya Bailey', false),
('Nodemailer Email Sending', 'Send emails from Node.js applications', true, 'Cole Rivera', false),
('Bull Job Queues', 'Background job processing with Bull', true, 'Savannah Cooper', true),
('Cron Job Scheduling', 'Schedule tasks with node-cron', true, 'Wyatt Richardson', false),
('Winston Logging', 'Application logging with Winston', true, 'Lily Cox', false),
('Morgan HTTP Logging', 'HTTP request logging middleware', true, 'Carson Howard', false),
('Multer File Uploads', 'Handle file uploads with Multer', false, 'Mackenzie Ward', true),
('Sharp Image Processing', 'Resize and optimize images with Sharp', true, 'Jaxon Torres', false),
('PDFKit Document Generation', 'Generate PDF documents in Node.js', true, 'Addison Peterson', true),
('ExcelJS Spreadsheet Handling', 'Work with Excel files in Node.js', true, 'Hudson Gray', false),
('CSV File Processing', 'Parse and generate CSV files', true, 'Aria Ramirez', false),
('Stream Processing', 'Handle large data with Node.js streams', true, 'Easton James', true),
('Buffer Manipulation', 'Work with binary data using Buffers', false, 'Zoe Watson', false),
('Child Processes', 'Execute system commands from Node.js', true, 'Landon Brooks', true),
('Cluster Module Scaling', 'Scale Node.js apps with cluster module', true, 'Peyton Kelly', true),
('PM2 Process Manager', 'Manage Node.js processes in production', true, 'Chase Sanders', false),
('Nginx Reverse Proxy', 'Configure Nginx as reverse proxy', true, 'Skylar Price', true),
('Apache Web Server', 'Host applications with Apache', false, 'Cameron Bennett', false),
('Load Balancing Strategies', 'Distribute traffic across multiple servers', true, 'Violet Wood', true),
('Microservices Architecture', 'Design and build microservices', true, 'Bentley Barnes', true),
('Message Queues RabbitMQ', 'Asynchronous messaging with RabbitMQ', true, 'Autumn Ross', true),
('Apache Kafka Streaming', 'Real-time data streaming with Kafka', false, 'Tristan Henderson', true),
('ElasticSearch Full-Text Search', 'Implement powerful search with ElasticSearch', true, 'Genesis Coleman', true),
('Algolia Search Integration', 'Add instant search with Algolia', true, 'Lincoln Jenkins', false),
('Stripe Payment Processing', 'Accept payments with Stripe API', true, 'Nova Perry', true),
('PayPal Integration', 'Integrate PayPal payment gateway', true, 'Grayson Powell', false),
('Firebase Authentication', 'User authentication with Firebase', false, 'Bella Long', false),
('Firebase Realtime Database', 'Build real-time apps with Firebase', true, 'Nolan Patterson', true),
('Firestore NoSQL Database', 'Cloud Firestore database operations', true, 'Stella Hughes', false),
('Supabase Backend', 'Open source Firebase alternative', true, 'Bryson Flores', true),
('Prisma ORM', 'Modern database toolkit and ORM', true, 'Elena Washington', true),
('Sequelize ORM', 'Promise-based Node.js ORM', true, 'Adrian Butler', false),
('TypeORM Database Abstraction', 'TypeScript-first ORM for Node.js', false, 'Paisley Simmons', true),
('Knex.js Query Builder', 'SQL query builder for Node.js', true, 'Colton Foster', false),
('PostgreSQL Advanced Queries', 'Master complex PostgreSQL queries', true, 'Layla Gonzales', true),
('MySQL Database Optimization', 'Optimize MySQL database performance', true, 'Axel Bryant', true),
('SQLite Embedded Database', 'Use SQLite for lightweight applications', true, 'Claire Alexander', false),
('Database Indexing Strategies', 'Improve query performance with indexes', true, 'Jace Russell', true),
('Database Normalization', 'Design normalized database schemas', false, 'Madelyn Griffin', false),
('Database Transactions', 'Ensure data consistency with transactions', true, 'Dominic Diaz', true),
('Database Migration Tools', 'Manage schema changes with migrations', true, 'Evelyn Hayes', false),
('Database Backup Strategies', 'Implement effective backup strategies', true, 'Sawyer Myers', true),
('Database Replication', 'Set up database replication for high availability', true, 'Anna Ford', true),
('Database Sharding', 'Scale databases with sharding techniques', false, 'Miles Hamilton', true),
('Time Series Databases', 'Store and query time-series data', true, 'Audrey Graham', false),
('Graph Databases Neo4j', 'Work with graph data in Neo4j', true, 'Maxwell Sullivan', true),
('DynamoDB NoSQL AWS', 'Amazon DynamoDB database operations', true, 'Penelope Wallace', true),
('CouchDB Document Database', 'Document-oriented database with CouchDB', false, 'Greyson Woods', false),
('Cassandra Distributed Database', 'Highly scalable distributed database', true, 'Lucy Kennedy', true),
('InfluxDB Time Series', 'Time series database for metrics', true, 'Everett Cole', false),
('Redis Data Structures', 'Advanced Redis data structures and commands', true, 'Lillian Chavez', true),
('Memcached Distributed Caching', 'High-performance distributed memory caching', true, 'Asher Owens', false),
('Varnish HTTP Cache', 'HTTP accelerator for content caching', false, 'Hannah Reynolds', true),
('CDN Content Delivery', 'Accelerate content delivery with CDNs', true, 'Declan Fisher', false),
('CloudFlare Setup', 'Configure CloudFlare for your website', true, 'Ellie Ellis', false),
('AWS S3 Storage', 'Object storage with Amazon S3', true, 'Levi Lawson', true),
('Google Cloud Storage', 'Store and retrieve data on Google Cloud', true, 'Scarlett Gibson', true),
('Azure Blob Storage', 'Microsoft Azure blob storage operations', false, 'Isaac Hunt', false),
('File System Operations', 'Work with files in Node.js', true, 'Chloe West', false),
('Path Module Utilities', 'Handle file paths with Node.js path module', true, 'Leo Brooks', false),
('Environment Variables', 'Manage configuration with environment variables', true, 'Zoey Barnes', false),
('dotenv Configuration', 'Load environment variables from .env files', true, 'Jack Kelly', false),
('Config Management', 'Centralized configuration management', true, 'Sophie Murray', false),
('Feature Flags', 'Implement feature toggles and flags', false, 'Owen McDonald', true),
('A/B Testing Implementation', 'Run experiments with A/B testing', true, 'Natalie Bryant', true),
('Analytics Integration', 'Track user behavior with analytics', true, 'Henry Alexander', false),
('Google Analytics Setup', 'Integrate Google Analytics tracking', true, 'Grace Russell', false),
('Mixpanel Event Tracking', 'Product analytics with Mixpanel', true, 'Sebastian Griffin', true),
('Sentry Error Tracking', 'Monitor and fix errors with Sentry', false, 'Ella Diaz', false),
('LogRocket Session Replay', 'Debug issues with session replay', true, 'Jackson Hayes', true),
('New Relic APM', 'Application performance monitoring', true, 'Camila Myers', true),
('Datadog Monitoring', 'Infrastructure and application monitoring', true, 'Aiden Ford', false),
('Prometheus Metrics', 'Collect and query metrics with Prometheus', true, 'Avery Hamilton', true),
('Grafana Dashboards', 'Visualize metrics with Grafana', false, 'Lucas Graham', false),
('ELK Stack Logging', 'Centralized logging with Elasticsearch, Logstash, Kibana', true, 'Mila Sullivan', true),
('Splunk Log Analysis', 'Enterprise log management with Splunk', true, 'Oliver Wallace', true),
('CI/CD with GitHub Actions', 'Automate workflows with GitHub Actions', true, 'Aria Woods', false),
('Jenkins Pipeline', 'Build CI/CD pipelines with Jenkins', true, 'Carter Kennedy', true),
('GitLab CI/CD', 'Continuous integration with GitLab', false, 'Scarlett Cole', false),
('CircleCI Configuration', 'Set up CircleCI for your projects', true, 'Wyatt Chavez', false),
('Travis CI Setup', 'Configure Travis CI builds', true, 'Ellie Owens', false),
('Terraform Infrastructure', 'Infrastructure as Code with Terraform', true, 'Eli Reynolds', true),
('Ansible Automation', 'Automate server configuration with Ansible', true, 'Nora Fisher', true),
('Chef Configuration Management', 'Manage infrastructure with Chef', false, 'Liam Ellis', false),
('Puppet Infrastructure', 'Infrastructure automation with Puppet', true, 'Abigail Lawson', true),
('Vagrant Development Environments', 'Create reproducible dev environments', true, 'Mason Gibson', false),
('VirtualBox Virtualization', 'Run virtual machines with VirtualBox', true, 'Emily Hunt', false),
('VMware Workstation', 'Desktop virtualization with VMware', false, 'Logan West', false),
('Linux Server Administration', 'Manage Linux servers effectively', true, 'Harper Brooks', true),
('Ubuntu Server Setup', 'Configure Ubuntu server from scratch', true, 'Ethan Barnes', false),
('CentOS Administration', 'Enterprise Linux with CentOS', true, 'Amelia Kelly', true),
('Debian Package Management', 'Manage packages on Debian systems', true, 'Alexander Murray', false),
('Bash Scripting', 'Automate tasks with Bash scripts', true, 'Evelyn McDonald', false),
('Shell Script Automation', 'Write powerful shell scripts', true, 'Benjamin Bryant', true),
('Systemd Service Management', 'Manage services with systemd', false, 'Charlotte Alexander', false),
('Crontab Task Scheduling', 'Schedule recurring tasks with cron', true, 'William Russell', false),
('SSH Key Authentication', 'Secure SSH access with key pairs', true, 'Mia Griffin', false),
('Firewall Configuration', 'Secure servers with firewall rules', true, 'James Diaz', true),
('iptables Network Filtering', 'Configure iptables firewall', true, 'Ava Hayes', true),
('UFW Firewall Setup', 'Simple firewall with UFW', false, 'Michael Myers', false),
('Fail2ban Intrusion Prevention', 'Protect against brute force attacks', true, 'Sophia Ford', true),
('SELinux Security', 'Enhanced security with SELinux', true, 'Daniel Hamilton', false),
('AppArmor Security Profiles', 'Application security with AppArmor', true, 'Isabella Graham', false),
('SSL Certificate Management', 'Manage SSL/TLS certificates', true, 'Matthew Sullivan', true),
('Let''s Encrypt Free SSL', 'Free SSL certificates with Let''s Encrypt', true, 'Emma Wallace', false),
('DNS Configuration', 'Configure DNS records properly', false, 'David Woods', false),
('CloudFlare DNS', 'Manage DNS with CloudFlare', true, 'Olivia Kennedy', false),
('Route 53 AWS DNS', 'Amazon Route 53 DNS service', true, 'Joseph Cole', true),
('Domain Registration', 'Register and manage domains', true, 'Madison Chavez', false),
('Email Server Setup', 'Configure email server with Postfix', true, 'Andrew Owens', true),
('SMTP Configuration', 'Set up SMTP email delivery', true, 'Elizabeth Reynolds', false),
('IMAP Email Access', 'Configure IMAP email retrieval', false, 'Joshua Fisher', false),
('SpamAssassin Spam Filter', 'Filter spam with SpamAssassin', true, 'Sofia Ellis', true),
('DKIM Email Authentication', 'Authenticate emails with DKIM', true, 'Christopher Lawson', false),
('SPF Record Configuration', 'Prevent email spoofing with SPF', true, 'Victoria Gibson', false),
('DMARC Email Policy', 'Email authentication policy with DMARC', true, 'Ryan Hunt', true),
('Mailgun Email API', 'Send emails via Mailgun API', true, 'Grace West', false),
('SendGrid Email Service', 'Transactional emails with SendGrid', false, 'Nicholas Brooks', false),
('AWS SES Email', 'Amazon Simple Email Service integration', true, 'Chloe Barnes', true),
('Twilio SMS Integration', 'Send SMS messages with Twilio', true, 'Jonathan Kelly', true),
('Slack Bot Development', 'Build Slack bots and integrations', true, 'Lily Murray', false),
('Discord Bot Creation', 'Create Discord bots with discord.js', true, 'Tyler McDonald', false),
('Telegram Bot API', 'Build Telegram bots', false, 'Zoe Bryant', true),
('WhatsApp Business API', 'Integrate WhatsApp messaging', true, 'Brandon Alexander', false),
('WebRTC Video Chat', 'Build video chat with WebRTC', true, 'Leah Russell', true),
('Agora Video SDK', 'Real-time video with Agora', true, 'Austin Griffin', true),
('Zoom API Integration', 'Integrate Zoom meetings into your app', false, 'Samantha Diaz', false),
('Jitsi Meet Integration', 'Open source video conferencing', true, 'Kevin Hayes', false),
('Screen Sharing Implementation', 'Add screen sharing to web apps', true, 'Anna Myers', true),
('WebSocket Communication', 'Real-time bidirectional communication', true, 'Dylan Ford', false),
('Server-Sent Events', 'One-way server push with SSE', true, 'Lauren Hamilton', false),
('Long Polling Techniques', 'Implement long polling for updates', false, 'Caleb Graham', false),
('Polling vs WebSockets', 'Choose the right real-time strategy', true, 'Hailey Sullivan', false),
('HTTP/2 Server Push', 'Optimize loading with HTTP/2 push', true, 'Connor Wallace', true),
('HTTP/3 and QUIC', 'Next generation HTTP protocol', true, 'Aubrey Woods', false),
('gRPC Remote Procedures', 'High performance RPC with gRPC', false, 'Ian Kennedy', true),
('Protocol Buffers', 'Efficient serialization with protobuf', true, 'Madeline Cole', false),
('Apache Thrift RPC', 'Cross-language RPC framework', true, 'Gavin Chavez', true),
('JSON-RPC API', 'Simple RPC with JSON', true, 'Bella Owens', false),
('XML-RPC Legacy Systems', 'Work with XML-RPC APIs', false, 'Jeremiah Reynolds', false),
('SOAP Web Services', 'Enterprise web services with SOAP', true, 'Brooklyn Fisher', true),
('REST API Best Practices', 'Design great RESTful APIs', true, 'Ezra Ellis', false),
('RESTful Resource Naming', 'Name API resources effectively', true, 'Ariana Lawson', false),
('API Versioning Strategies', 'Version your APIs properly', true, 'Julian Gibson', true),
('API Documentation Swagger', 'Document APIs with Swagger/OpenAPI', true, 'Nevaeh Hunt', false),
('Postman API Testing', 'Test APIs with Postman', false, 'Isaiah West', false),
('Insomnia REST Client', 'API development with Insomnia', true, 'Aaliyah Brooks', false),
('API Rate Limiting Best Practices', 'Implement fair rate limiting', true, 'Carson Barnes', true),
('API Pagination Strategies', 'Handle large datasets with pagination', true, 'Kennedy Kelly', false),
('API Filtering and Sorting', 'Implement query filtering and sorting', true, 'Tristan Murray', false),
('API Error Handling', 'Handle and communicate API errors', true, 'Sadie McDonald', true),
('HTTP Status Codes', 'Use HTTP status codes correctly', false, 'Jameson Bryant', false),
('API Security Best Practices', 'Secure your APIs effectively', true, 'Piper Alexander', true),
('API Keys Management', 'Manage and rotate API keys', true, 'Cole Russell', false),
('OAuth 2.0 Scopes', 'Implement granular permissions', true, 'Lydia Griffin', true),
('OpenID Connect', 'Identity layer on OAuth 2.0', true, 'Miguel Diaz', false),
('SAML Authentication', 'Enterprise SSO with SAML', false, 'Isabelle Hayes', true),
('LDAP Directory Services', 'Integrate with LDAP/Active Directory', true, 'Zachary Myers', true),
('Multi-Factor Authentication', 'Add MFA to your applications', true, 'Vivian Ford', true),
('Biometric Authentication', 'Implement fingerprint and face recognition', true, 'Mateo Hamilton', false),
('Magic Link Authentication', 'Passwordless login with email links', true, 'Claire Graham', false),
('QR Code Authentication', 'Login with QR code scanning', false, 'Jaxson Sullivan', true),
('CAPTCHA Implementation', 'Prevent bots with CAPTCHA', true, 'Alice Wallace', false),
('reCAPTCHA v3', 'Invisible bot protection with reCAPTCHA', true, 'Brody Woods', false),
('Session Management', 'Secure session handling', true, 'Valentina Kennedy', true),
('Cookie Security', 'Secure cookie configuration', true, 'Wesley Cole', false),
('Local Storage Security', 'Safely use browser local storage', false, 'Kaylee Chavez', false),
('Session Storage Usage', 'Session storage best practices', true, 'Parker Owens', false),
('IndexedDB Browser Database', 'Client-side database with IndexedDB', true, 'Peyton Reynolds', true),
('Web Workers Background Tasks', 'Run tasks in background threads', true, 'Ryker Fisher', false),
('Service Workers PWA', 'Build offline-capable apps', true, 'Eliana Ellis', true),
('Push Notifications Web', 'Send push notifications to browsers', false, 'Miles Lawson', false),
('Notification API Browser', 'Display browser notifications', true, 'Delilah Gibson', true),
('Geolocation API', 'Access user location in browsers', true, 'Ashton Hunt', false),
('Web Bluetooth API', 'Connect to Bluetooth devices', true, 'Ruby West', false),
('Web USB API', 'Access USB devices from web', false, 'Finn Brooks', true),
('WebGL 3D Graphics', 'Render 3D graphics in browsers', true, 'Jade Barnes', true),
('Three.js 3D Library', 'Create 3D experiences with Three.js', true, 'Knox Kelly', false),
('Canvas API Drawing', 'Draw graphics with Canvas API', true, 'Marley Murray', false),
('SVG Graphics', 'Scalable vector graphics in web', true, 'Beckham McDonald', true),
('D3.js Data Visualization', 'Visualize data with D3.js', false, 'Raelynn Bryant', false),
('Chart.js Simple Charts', 'Create charts with Chart.js', true, 'Roman Alexander', false),
('Highcharts Interactive Charts', 'Interactive charts with Highcharts', true, 'Emilia Russell', true),
('Recharts React Charts', 'Composable charts for React', true, 'Rowan Griffin', false),
('Victory Charts React', 'Modular charting for React', true, 'Esther Diaz', false),
('Plotly.js Graphing', 'Scientific charts with Plotly', false, 'Remington Hayes', true),
('Leaflet Maps', 'Interactive maps with Leaflet', true, 'Eden Myers', false),
('Google Maps API', 'Integrate Google Maps', true, 'Archer Ford', true),
('Mapbox GL JS', 'Vector maps with Mapbox', true, 'Ember Hamilton', true),
('OpenLayers Mapping', 'Open source web mapping', false, 'Crew Graham', false),
('Geocoding Services', 'Convert addresses to coordinates', true, 'Octavia Sullivan', false),
('Reverse Geocoding', 'Convert coordinates to addresses', true, 'Karter Wallace', false),
('Routing and Directions', 'Calculate routes between locations', true, 'Freya Woods', true),
('Distance Matrix API', 'Calculate travel distances and times', true, 'Hendrix Kennedy', false),
('Places API Search', 'Search for places and businesses', false, 'Sloane Cole', false),
('Street View Integration', 'Embed Google Street View', true, 'Ronan Chavez', true),
('Image Optimization', 'Optimize images for web delivery', true, 'Lyla Owens', false),
('Lazy Loading Images', 'Load images on demand', true, 'Greyson Reynolds', false),
('Responsive Images', 'Serve appropriate image sizes', true, 'Harley Fisher', false),
('WebP Image Format', 'Use modern WebP images', false, 'Juniper Ellis', true),
('AVIF Image Format', 'Next-gen image format AVIF', true, 'Beau Lawson', false),
('Image CDN Cloudinary', 'Manage and deliver images with Cloudinary', true, 'Magnolia Gibson', true),
('Imgix Image Processing', 'Real-time image manipulation', true, 'Kolton Hunt', false),
('Video Streaming', 'Stream video content efficiently', true, 'Journee West', true),
('HLS Video Streaming', 'HTTP Live Streaming protocol', false, 'Kade Brooks', false),
('DASH Video Streaming', 'Dynamic Adaptive Streaming', true, 'Kendra Barnes', true),
('Video.js Player', 'Open source HTML5 video player', true, 'Anderson Kelly', false),
('Plyr Media Player', 'Simple media player library', true, 'Lennon Murray', false),
('YouTube API Integration', 'Embed and control YouTube videos', true, 'Nellie McDonald', false),
('Vimeo API', 'Integrate Vimeo video platform', false, 'Briggs Bryant', true),
('FFmpeg Video Processing', 'Process videos with FFmpeg', true, 'Rosalie Alexander', true),
('Video Transcoding', 'Convert videos between formats', true, 'Malachi Russell', false),
('Video Thumbnails', 'Generate video thumbnail images', true, 'Millie Griffin', false),
('Subtitles and Captions', 'Add subtitles to videos', true, 'Bowen Diaz', true),
('Audio Processing Web', 'Process audio in browsers', false, 'Kinsley Hayes', false),
('Web Audio API', 'Create and manipulate audio', true, 'Shiloh Myers', true),
('Howler.js Audio Library', 'Audio library for web', true, 'Remi Ford', false),
('Tone.js Music Framework', 'Create music in the browser', true, 'Stevie Hamilton', false),
('Speech Recognition Web', 'Convert speech to text', false, 'Ellis Graham', true),
('Speech Synthesis API', 'Text-to-speech in browsers', true, 'Presley Sullivan', false),
('Voice Commands Web', 'Implement voice controls', true, 'Lennox Wallace', true),
('Audio Visualization', 'Visualize audio frequencies', true, 'Palmer Woods', false),
('Music Streaming', 'Build music streaming features', true, 'Royal Kennedy', true),
('Podcast Player Development', 'Create podcast player apps', false, 'Azariah Cole', false),
('RSS Feed Parsing', 'Parse and display RSS feeds', true, 'Indie Chavez', false),
('Atom Feed Generation', 'Generate Atom syndication feeds', true, 'Legacy Owens', false),
('XML Parsing', 'Parse XML documents in Node.js', true, 'Reign Reynolds', false),
('JSON Schema Validation', 'Validate JSON with schemas', true, 'Oakley Fisher', true),
('YAML Configuration Files', 'Use YAML for configuration', false, 'Armani Ellis', false),
('TOML Config Format', 'Configuration with TOML', true, 'Sage Lawson', false),
('Markdown Parsing', 'Parse and render Markdown', true, 'Dakotah Gibson', false),
('Markdown-it Renderer', 'Powerful Markdown parser', true, 'Kamryn Hunt', false),
('MDX React Markdown', 'Use JSX in Markdown documents', true, 'Cassidy West', true),
('Rich Text Editors', 'Implement rich text editing', false, 'Justice Brooks', false),
('Draft.js Text Editor', 'Rich text editor framework by Facebook', true, 'Emerson Barnes', true),
('Slate.js Editor Framework', 'Customizable rich text editor', true, 'Skyler Kelly', false),
('Quill Rich Text Editor', 'Modern WYSIWYG editor', true, 'Lennon Murray', false),
('TinyMCE Editor', 'Advanced WYSIWYG editor', true, 'Morgan McDonald', true),
('CKEditor Integration', 'Full-featured text editor', false, 'Phoenix Bryant', false),
('Contenteditable API', 'Make elements editable in browser', true, 'River Alexander', false),
('Code Editor Monaco', 'VS Code''s editor for the web', true, 'Sage Russell', true),
('CodeMirror Editor', 'Versatile text editor for code', true, 'Blair Griffin', false),
('Ace Code Editor', 'Embeddable code editor', true, 'Reese Diaz', false),
('Syntax Highlighting Prism', 'Lightweight syntax highlighting', false, 'Quinn Hayes', true),
('Highlight.js Code', 'Syntax highlighting for the web', true, 'Avery Myers', false),
('Code Formatting Prettier', 'Opinionated code formatter', true, 'Taylor Ford', false),
('Code Linting ESLint', 'Find and fix code problems', true, 'Casey Hamilton', false),
('TypeScript Compiler API', 'Programmatic TypeScript compilation', true, 'Jordan Graham', true),
('Babel Plugin Development', 'Create custom Babel plugins', false, 'Cameron Sullivan', false),
('AST Abstract Syntax Tree', 'Parse and manipulate code', true, 'Riley Wallace', true),
('Sourcemap Generation', 'Generate source maps for debugging', true, 'Hayden Woods', false),
('Code Coverage Istanbul', 'Measure code coverage', true, 'Finley Kennedy', false),
('Test-Driven Development', 'TDD methodology and practices', true, 'Emery Cole', true),
('Behavior-Driven Development', 'BDD with Cucumber', false, 'Blake Chavez', false),
('Integration Testing', 'Test component integration', true, 'Alexis Owens', false),
('E2E Testing Best Practices', 'End-to-end testing strategies', true, 'Peyton Reynolds', true),
('Visual Regression Testing', 'Catch visual bugs automatically', true, 'Sage Fisher', true),
('Percy Visual Testing', 'Automated visual review', false, 'Drew Ellis', false),
('Chromatic Storybook Testing', 'Visual testing for Storybook', true, 'Charlie Lawson', false),
('Snapshot Testing Jest', 'Component snapshot testing', true, 'Rowan Gibson', false),
('Mocking and Stubbing', 'Mock dependencies in tests', true, 'Finley Hunt', false),
('Test Fixtures', 'Manage test data effectively', true, 'Tatum West', true),
('Factory Pattern Testing', 'Generate test data with factories', false, 'Skylar Brooks', false),
('Faker.js Test Data', 'Generate fake data for testing', true, 'Kennedy Barnes', false),
('Sinon.js Test Spies', 'Spies, stubs, and mocks', true, 'Morgan Kelly', true),
('Nock HTTP Mocking', 'Mock HTTP requests in Node.js', true, 'River Murray', false),
('MSW Mock Service Worker', 'API mocking for browsers and Node', true, 'Phoenix McDonald', false),
('Testing Library React', 'Test React components properly', false, 'Sage Bryant', true),
('Enzyme React Testing', 'Testing utility for React', true, 'Blair Alexander', false),
('Vue Test Utils', 'Official testing library for Vue', true, 'Reese Russell', true),
('Angular TestBed', 'Test Angular applications', true, 'Quinn Griffin', false),
('Puppeteer Testing', 'Headless browser testing', true, 'Avery Diaz', true),
('Playwright Testing', 'Cross-browser end-to-end testing', false, 'Taylor Hayes', false),
('Selenium WebDriver', 'Browser automation framework', true, 'Casey Myers', true),
('TestCafe E2E Testing', 'Node.js end-to-end testing', true, 'Jordan Ford', false),
('Nightwatch.js Testing', 'Browser testing framework', true, 'Cameron Hamilton', false),
('WebdriverIO Testing', 'Next-gen browser automation', true, 'Riley Graham', true),
('Detox Mobile Testing', 'E2E testing for mobile apps', false, 'Hayden Sullivan', false),
('Appium Mobile Automation', 'Cross-platform mobile testing', true, 'Finley Wallace', true),
('XCTest iOS Testing', 'Native iOS testing framework', true, 'Emery Woods', false),
('Espresso Android Testing', 'Android UI testing framework', true, 'Blake Kennedy', false),
('React Native Testing', 'Test React Native apps', true, 'Alexis Cole', true),
('Flutter Testing', 'Test Flutter applications', false, 'Peyton Chavez', false),
('Ionic Testing', 'Test Ionic hybrid apps', true, 'Sage Owens', false),
('Cordova Plugin Development', 'Create Cordova plugins', true, 'Drew Reynolds', true),
('Capacitor Native Bridge', 'Native functionality for web apps', true, 'Charlie Fisher', false),
('Electron Desktop Apps', 'Build desktop apps with web tech', true, 'Rowan Ellis', true),
('Electron Forge', 'Electron development toolkit', false, 'Finley Lawson', false),
('NW.js Desktop Apps', 'Alternative to Electron', true, 'Tatum Gibson', false),
('Tauri Lightweight Desktop', 'Build smaller desktop apps', true, 'Skylar Hunt', true),
('PWA Desktop Installation', 'Install PWAs on desktop', true, 'Kennedy West', false),
('WebView Integration', 'Embed web content in native apps', true, 'Morgan Brooks', false),
('Deep Linking Apps', 'Handle deep links in apps', false, 'River Barnes', true),
('Universal Links iOS', 'iOS deep linking with universal links', true, 'Phoenix Kelly', false),
('App Links Android', 'Android deep linking', true, 'Sage Murray', true),
('QR Code Generation', 'Generate QR codes programmatically', true, 'Blair McDonald', false),
('QR Code Scanning', 'Scan QR codes in web and mobile', true, 'Reese Bryant', false),
('Barcode Scanning', 'Read barcodes in applications', false, 'Quinn Alexander', true),
('NFC Communication', 'Near Field Communication in apps', true, 'Avery Russell', false),
('Beacon Technology', 'Bluetooth beacon integration', true, 'Taylor Griffin', true),
('Location-Based Services', 'Build location-aware features', true, 'Casey Diaz', false),
('Augmented Reality Web', 'AR experiences in browsers', false, 'Jordan Hayes', true),
('AR.js Augmented Reality', 'Lightweight AR for web', true, 'Cameron Myers', true),
('Virtual Reality WebVR', 'VR experiences on the web', true, 'Riley Ford', false),
('A-Frame VR Framework', 'Build VR with HTML', true, 'Hayden Hamilton', false),
('React VR Development', 'Create VR with React', false, 'Finley Graham', true),
('Unity WebGL Export', 'Export Unity games to web', true, 'Emery Sullivan', false),
('Phaser Game Framework', 'HTML5 game development', true, 'Blake Wallace', true),
('PixiJS 2D Rendering', 'Fast 2D WebGL renderer', true, 'Alexis Woods', false),
('Babylon.js 3D Engine', 'Powerful 3D engine for web', true, 'Peyton Kennedy', true),
('Matter.js Physics', '2D physics engine for web', false, 'Sage Cole', false),
('Cannon.js 3D Physics', '3D physics engine', true, 'Drew Chavez', false),
('GSAP Animation Library', 'Professional animation for web', true, 'Charlie Owens', true),
('Anime.js Animations', 'Lightweight animation library', true, 'Rowan Reynolds', false),
('Framer Motion React', 'Production-ready React animations', true, 'Finley Fisher', true),
('React Spring Animations', 'Spring-physics animations for React', false, 'Tatum Ellis', false),
('Lottie Animations', 'Render After Effects animations', true, 'Skylar Lawson', false),
('Rive Interactive Animations', 'Real-time interactive graphics', true, 'Kennedy Gibson', true),
('CSS Animations', 'Create animations with CSS', true, 'Morgan Hunt', false),
('CSS Transitions', 'Smooth state changes with CSS', true, 'River West', false),
('Keyframe Animations', 'Complex animations with keyframes', false, 'Phoenix Brooks', false),
('Scroll Animations', 'Trigger animations on scroll', true, 'Sage Barnes', true),
('Parallax Scrolling', 'Create depth with parallax', true, 'Blair Kelly', false),
('Infinite Scroll Implementation', 'Load content on scroll', true, 'Reese Murray', false),
('Virtual Scrolling', 'Efficiently render large lists', true, 'Quinn McDonald', true),
('Intersection Observer API', 'Detect element visibility', true, 'Avery Bryant', false),
('Mutation Observer API', 'Watch DOM changes', false, 'Taylor Alexander', false),
('Resize Observer API', 'Track element size changes', true, 'Casey Russell', false),
('Performance Observer API', 'Monitor performance metrics', true, 'Jordan Griffin', true),
('Web Vitals Metrics', 'Measure Core Web Vitals', true, 'Cameron Diaz', false),
('Lighthouse Performance Audit', 'Audit and improve performance', true, 'Riley Hayes', true),
('PageSpeed Insights', 'Analyze page performance', false, 'Hayden Myers', false),
('Bundle Size Analysis', 'Optimize bundle size', true, 'Finley Ford', false),
('Code Splitting Webpack', 'Split code for faster loading', true, 'Emery Hamilton', true),
('Tree Shaking', 'Eliminate dead code', true, 'Blake Graham', false),
('Minification Optimization', 'Minify JavaScript and CSS', true, 'Alexis Sullivan', false),
('Compression Gzip Brotli', 'Compress assets for delivery', true, 'Peyton Wallace', true),
('Resource Hints Preload', 'Optimize resource loading', false, 'Sage Woods', false),
('Critical CSS Extraction', 'Extract critical CSS', true, 'Drew Kennedy', false),
('Async CSS Loading', 'Load CSS asynchronously', true, 'Charlie Cole', false),
('Font Loading Strategies', 'Optimize web font loading', true, 'Rowan Chavez', false),
('FOIT FOUT Prevention', 'Prevent font loading issues', true, 'Finley Owens', true),
('Variable Fonts', 'Use variable fonts effectively', false, 'Tatum Reynolds', false),
('Icon Fonts vs SVG', 'Choose the right icon format', true, 'Skylar Fisher', false),
('SVG Sprite Optimization', 'Optimize SVG icons', true, 'Kennedy Ellis', true),
('Image Sprites CSS', 'Combine images into sprites', true, 'Morgan Lawson', false),
('Data URIs Inline Images', 'Embed images in CSS/HTML', false, 'River Gibson', false),
('Base64 Encoding', 'Encode binary data as text', true, 'Phoenix Hunt', false),
('URL Shortening Services', 'Build URL shortener', true, 'Sage West', true),
('Link Previews Generation', 'Generate rich link previews', true, 'Blair Brooks', false),
('Meta Tags SEO', 'Optimize meta tags for SEO', true, 'Reese Barnes', false),
('Open Graph Protocol', 'Rich social media previews', true, 'Quinn Kelly', true),
('Twitter Cards', 'Optimize sharing on Twitter', false, 'Avery Murray', false),
('Schema.org Structured Data', 'Add structured data markup', true, 'Taylor McDonald', true),
('JSON-LD Implementation', 'Structured data with JSON-LD', true, 'Casey Bryant', false),
('Sitemap Generation', 'Generate XML sitemaps', true, 'Jordan Alexander', false),
('Robots.txt Configuration', 'Control search engine crawling', true, 'Cameron Russell', false),
('Canonical URLs', 'Handle duplicate content', true, 'Riley Griffin', true),
('Internationalization SEO', 'SEO for multilingual sites', false, 'Hayden Diaz', false),
('Hreflang Tags', 'Language and regional targeting', true, 'Finley Hayes', false),
('Server-Side Rendering SEO', 'Optimize SSR for search engines', true, 'Emery Myers', true),
('Static Site Generation', 'Build static sites for performance', true, 'Blake Ford', true),
('Incremental Static Regeneration', 'Update static pages incrementally', false, 'Alexis Hamilton', false),
('Edge Computing Cloudflare Workers', 'Run code at the edge', true, 'Peyton Graham', true),
('AWS Lambda Functions', 'Serverless functions on AWS', true, 'Sage Sullivan', false),
('Azure Functions', 'Serverless compute on Azure', true, 'Drew Wallace', false),
('Google Cloud Functions', 'Event-driven serverless functions', true, 'Charlie Woods', true),
('Netlify Functions', 'Serverless functions on Netlify', false, 'Rowan Kennedy', false),
('Vercel Serverless Functions', 'API routes on Vercel', true, 'Finley Cole', false),
('API Gateway AWS', 'Manage APIs with API Gateway', true, 'Tatum Chavez', true),
('GraphQL Federation', 'Distributed GraphQL architecture', true, 'Skylar Owens', false),
('Apollo Server GraphQL', 'Build GraphQL servers', true, 'Kennedy Reynolds', true),
('Apollo Client React', 'GraphQL client for React', false, 'Morgan Fisher', false),
('Relay GraphQL Client', 'Facebook''s GraphQL framework', true, 'River Ellis', true),
('Hasura GraphQL Engine', 'Instant GraphQL on databases', true, 'Phoenix Lawson', false),
('Prisma GraphQL', 'Type-safe database access', true, 'Sage Gibson', false),
('GraphQL Subscriptions', 'Real-time GraphQL', true, 'Blair Hunt', true),
('GraphQL Code Generator', 'Generate types from schema', false, 'Reese West', false),
('GraphQL Schema Design', 'Design effective GraphQL schemas', true, 'Quinn Brooks', false),
('GraphQL Caching', 'Cache GraphQL queries effectively', true, 'Avery Barnes', true),
('GraphQL Pagination', 'Implement pagination in GraphQL', true, 'Taylor Kelly', false),
('GraphQL Error Handling', 'Handle errors in GraphQL', true, 'Casey Murray', false),
('GraphQL Batching', 'Batch GraphQL requests', false, 'Jordan McDonald', true),
('GraphQL DataLoader', 'Solve N+1 query problem', true, 'Cameron Bryant', false),
('Microservices Communication', 'Service-to-service communication', true, 'Riley Alexander', true),
('API Gateway Pattern', 'Centralized API management', true, 'Hayden Russell', true),
('Service Mesh Istio', 'Manage microservices with Istio', false, 'Finley Griffin', false),
('Circuit Breaker Pattern', 'Handle service failures', true, 'Emery Diaz', true),
('Retry Logic Implementation', 'Implement retry strategies', true, 'Blake Hayes', false),
('Bulkhead Pattern', 'Isolate service resources', true, 'Alexis Myers', false),
('Event-Driven Architecture', 'Build event-driven systems', true, 'Peyton Ford', true),
('CQRS Pattern', 'Command Query Responsibility Segregation', false, 'Sage Hamilton', false),
('Event Sourcing', 'Store state as events', true, 'Drew Graham', true),
('Saga Pattern Distributed', 'Manage distributed transactions', true, 'Charlie Sullivan', false),
('Domain-Driven Design', 'DDD principles and patterns', true, 'Rowan Wallace', true),
('Clean Architecture', 'Build maintainable systems', false, 'Finley Woods', false),
('Hexagonal Architecture', 'Ports and adapters pattern', true, 'Tatum Kennedy', false),
('Onion Architecture', 'Layered architecture pattern', true, 'Skylar Cole', true),
('Repository Pattern', 'Abstract data access layer', true, 'Kennedy Chavez', false),
('Unit of Work Pattern', 'Manage transactions effectively', true, 'Morgan Owens', false),
('Factory Pattern OOP', 'Object creation patterns', false, 'River Reynolds', true),
('Builder Pattern', 'Construct complex objects', true, 'Phoenix Fisher', false),
('Singleton Pattern', 'Ensure single instance', true, 'Sage Ellis', false),
('Observer Pattern', 'Subscribe to events', true, 'Blair Lawson', false),
('Strategy Pattern', 'Encapsulate algorithms', true, 'Reese Gibson', true),
('Decorator Pattern', 'Add behavior dynamically', false, 'Quinn Hunt', false),
('Adapter Pattern', 'Convert interfaces', true, 'Avery West', false),
('Facade Pattern', 'Simplify complex subsystems', true, 'Taylor Brooks', true),
('Proxy Pattern', 'Control object access', true, 'Casey Barnes', false),
('Command Pattern', 'Encapsulate requests', true, 'Jordan Kelly', false),
('Template Method Pattern', 'Define algorithm skeleton', false, 'Cameron Murray', true),
('Iterator Pattern', 'Traverse collections', true, 'Riley McDonald', false),
('Composite Pattern', 'Tree structures', true, 'Hayden Bryant', true),
('State Pattern', 'Object state behavior', true, 'Finley Alexander', false),
('Dependency Injection', 'Inversion of control pattern', true, 'Emery Russell', true),
('Service Locator Pattern', 'Centralize service access', false, 'Blake Griffin', false),
('Null Object Pattern', 'Handle null references', true, 'Alexis Diaz', false),
('Object Pool Pattern', 'Reuse expensive objects', true, 'Peyton Hayes', false),
('Flyweight Pattern', 'Share common state', true, 'Sage Myers', true),
('Chain of Responsibility', 'Pass requests along chain', false, 'Drew Ford', false),
('Mediator Pattern', 'Centralize complex communications', true, 'Charlie Hamilton', false),
('Memento Pattern', 'Capture object state', true, 'Rowan Graham', true),
('Visitor Pattern', 'Separate algorithms from objects', true, 'Finley Sullivan', false),
('Interpreter Pattern', 'Interpret language grammar', false, 'Tatum Wallace', false),
('Specification Pattern', 'Business rules encapsulation', true, 'Skylar Woods', false),
('Module Pattern JavaScript', 'Encapsulation in JavaScript', true, 'Kennedy Kennedy', true),
('Revealing Module Pattern', 'Expose public API', true, 'Morgan Cole', false),
('Prototype Pattern', 'Clone objects efficiently', true, 'River Chavez', false),
('Mixin Pattern', 'Share behavior across objects', false, 'Phoenix Owens', true),
('Higher-Order Functions', 'Functions that return functions', true, 'Sage Reynolds', false),
('Currying Functions', 'Transform multi-arg functions', true, 'Blair Fisher', false),
('Partial Application', 'Pre-fill function arguments', true, 'Reese Ellis', false),
('Function Composition', 'Combine simple functions', true, 'Quinn Lawson', true),
('Pipe Operator', 'Chain function calls', false, 'Avery Gibson', false),
('Memoization Optimization', 'Cache function results', true, 'Taylor Hunt', true),
('Lazy Evaluation', 'Delay computation until needed', true, 'Casey West', false),
('Recursion Techniques', 'Solve problems recursively', true, 'Jordan Brooks', false),
('Tail Call Optimization', 'Optimize recursive functions', true, 'Cameron Barnes', true),
('Generator Functions', 'Pausable functions in JavaScript', false, 'Riley Kelly', false),
('Async Iterators', 'Iterate asynchronous data', true, 'Hayden Murray', false),
('Promises Advanced', 'Master JavaScript Promises', true, 'Finley McDonald', true),
('Async/Await Best Practices', 'Write clean asynchronous code', true, 'Emery Bryant', false),
('Error Handling Async', 'Handle errors in async code', true, 'Blake Alexander', false),
('Promise.all Parallel Execution', 'Run promises in parallel', false, 'Alexis Russell', true),
('Promise.race Use Cases', 'Race multiple promises', true, 'Peyton Griffin', false),
('Promise.allSettled', 'Wait for all promises regardless', true, 'Sage Diaz', false),
('Promise.any Usage', 'First fulfilled promise', true, 'Drew Hayes', false),
('AbortController Cancel Requests', 'Cancel fetch requests', true, 'Charlie Myers', true),
('Timeout Promises', 'Add timeouts to async operations', false, 'Rowan Ford', false),
('Retry Failed Promises', 'Implement promise retry logic', true, 'Finley Hamilton', true),
('Debouncing Functions', 'Limit function execution rate', true, 'Tatum Graham', false),
('Throttling Functions', 'Control function call frequency', true, 'Skylar Sullivan', false),
('RequestAnimationFrame', 'Optimize animations', true, 'Kennedy Wallace', true),
('RequestIdleCallback', 'Schedule low-priority work', false, 'Morgan Woods', false),
('Intersection Observer Lazy Load', 'Lazy load with observers', true, 'River Kennedy', false),
('Infinite Scroll Performance', 'Optimize infinite scrolling', true, 'Phoenix Cole', true),
('Virtual DOM React', 'Understanding React''s Virtual DOM', true, 'Sage Chavez', false),
('React Fiber Architecture', 'React''s reconciliation engine', false, 'Blair Owens', false),
('React Hooks Deep Dive', 'Master React Hooks', true, 'Reese Reynolds', true),
('Custom Hooks React', 'Create reusable custom hooks', true, 'Quinn Fisher', false),
('useEffect Best Practices', 'Use useEffect correctly', true, 'Avery Ellis', true),
('useCallback Optimization', 'Optimize with useCallback', true, 'Taylor Lawson', false),
('useMemo Performance', 'Memoize expensive computations', false, 'Casey Gibson', false),
('useContext Global State', 'Share state with Context', true, 'Jordan Hunt', false),
('useReducer Complex State', 'Manage complex state logic', true, 'Cameron West', true),
('useRef DOM Access', 'Access DOM with useRef', true, 'Riley Brooks', false),
('useImperativeHandle', 'Customize ref exposure', false, 'Hayden Barnes', true),
('useLayoutEffect Usage', 'Synchronous effects', true, 'Finley Kelly', false),
('useTransition React 18', 'Mark updates as transitions', true, 'Emery Murray', false),
('useDeferredValue React 18', 'Defer non-urgent updates', true, 'Blake McDonald', false),
('React Suspense Data Fetching', 'Declarative loading states', false, 'Alexis Bryant', true),
('React Error Boundaries', 'Catch React errors gracefully', true, 'Peyton Alexander', true),
('React Portals', 'Render outside parent hierarchy', true, 'Sage Russell', false),
('React Fragments', 'Group elements without wrapper', true, 'Drew Griffin', false),
('React StrictMode', 'Detect potential problems', true, 'Charlie Diaz', false),
('React Profiler', 'Measure rendering performance', false, 'Rowan Hayes', true),
('React DevTools', 'Debug React applications', true, 'Finley Myers', false),
('Component Composition React', 'Build with composition', true, 'Tatum Ford', false),
('Render Props Pattern', 'Share code using render props', true, 'Skylar Hamilton', true),
('Higher-Order Components', 'Enhance components with HOCs', false, 'Kennedy Graham', false),
('Compound Components Pattern', 'Flexible component APIs', true, 'Morgan Sullivan', true),
('Controlled Components', 'Manage form state in React', true, 'River Wallace', false),
('Uncontrolled Components', 'Use refs for form inputs', true, 'Phoenix Woods', false),
('Form Validation React', 'Validate forms effectively', true, 'Sage Kennedy', true),
('Dynamic Forms React', 'Build dynamic form fields', false, 'Blair Cole', false),
('Multi-Step Forms', 'Create wizard-style forms', true, 'Reese Chavez', false),
('File Upload React', 'Handle file uploads', true, 'Quinn Owens', true),
('Drag and Drop React', 'Implement drag and drop', true, 'Avery Reynolds', false),
('React DnD Library', 'Drag and drop with react-dnd', false, 'Taylor Fisher', false),
('React Beautiful DnD', 'Beautiful drag and drop lists', true, 'Casey Ellis', true),
('Sortable Lists React', 'Create sortable list components', true, 'Jordan Lawson', false),
('Data Tables React', 'Build feature-rich tables', true, 'Cameron Gibson', false),
('React Table Library', 'Headless table component', true, 'Riley Hunt', true),
('Pagination React', 'Implement pagination', false, 'Hayden West', false),
('Search Filtering React', 'Filter data in real-time', true, 'Finley Brooks', false),
('Autocomplete Search', 'Build autocomplete functionality', true, 'Emery Barnes', true),
('Typeahead Suggestions', 'Show search suggestions', true, 'Blake Kelly', false),
('Modal Dialogs React', 'Create accessible modals', true, 'Alexis Murray', false),
('Toast Notifications', 'Show toast messages', false, 'Peyton McDonald', true),
('Tooltip Components', 'Build accessible tooltips', true, 'Sage Bryant', false),
('Dropdown Menus React', 'Create dropdown components', true, 'Drew Alexander', false),
('Accordion Components', 'Expandable content sections', true, 'Charlie Russell', false),
('Tabs Component React', 'Tabbed interface component', true, 'Rowan Griffin', true),
('Carousel Slider React', 'Build image carousels', false, 'Finley Diaz', false),
('Image Gallery React', 'Create photo galleries', true, 'Tatum Hayes', true),
('Lightbox Component', 'Full-screen image viewer', true, 'Skylar Myers', false),
('Infinite Carousel', 'Continuous sliding carousel', true, 'Kennedy Ford', false),
('Skeleton Loading States', 'Improve perceived performance', true, 'Morgan Hamilton', true),
('Shimmer Effect Loading', 'Animated loading placeholders', false, 'River Graham', false),
('Progress Bars React', 'Show operation progress', true, 'Phoenix Sullivan', false),
('Step Progress Indicators', 'Multi-step process indicators', true, 'Sage Wallace', false),
('Badge Components', 'Notification badges', true, 'Blair Woods', false),
('Avatar Components', 'User profile images', true, 'Reese Kennedy', true),
('Breadcrumb Navigation', 'Hierarchical navigation', false, 'Quinn Cole', false),
('Sidebar Navigation', 'Collapsible sidebar menus', true, 'Avery Chavez', false),
('Mega Menu Navigation', 'Large navigation menus', true, 'Taylor Owens', true),
('Mobile Navigation Drawer', 'Slide-out mobile menu', true, 'Casey Reynolds', false),
('Bottom Navigation Mobile', 'Mobile bottom tab bar', false, 'Jordan Fisher', false),
('Sticky Header Navigation', 'Fixed navigation on scroll', true, 'Cameron Ellis', true),
('Animated Hamburger Menu', 'Animated mobile menu icon', true, 'Riley Lawson', false);
